language: node_js

node_js:
  - '11'

branches:
  only:
    - master

script:
  - yarn
  - yarn build
  - yarn test
  - yarn test:coverage

after_success:
  - surge --project ./build --domain https://javascript-design-patterns.surge.sh
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
