language: node_js

branches:
  only:
    - master
    - /^greenkeeper.*$/

script:
  - yarn
  - yarn build
  - yarn test
  - yarn test:coverage

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

deploy:
  provider: surge
  project: ./build
  domain: https://design-patterns-javascript.surge.sh
  skip_cleanup: true
