language: node_js

node_js:
  - '11'

branches:
  only:
    - master

script:
  - yarn
  - yarn build
  - yarn test

after_success:
  - yarn test:coverage
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

deploy:
  provider: surge
  project: ./build
  domain: https://javascript-design-patterns.surge.sh
  skip_cleanup: true
