language: node_js

node_js:
  - '11'
  - node

branches:
  only:
    - master

script:
  - yarn
  - yarn build
  - yarn test
  - yarn test:coveralls

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
