language: node_js

node_js:
  - '11'

branches:
  only:
    - master

script:
  - yarn
  - yarn build
  - yarn test

after_script:
  - cat ./coverage/**/lcov.info | ./node_modules/coveralls/bin/coveralls.js
