language: node_js

node_js:
  - '11'

branches:
  only:
    - master

script:
  - yarn
  - yarn build
  - yarn test
  - yarn test:coverage

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

deploy:
  api_key:
    secure: wEOqSHFOSK6wWAd6OL8PgmXT9n+bHeq30OzmRhVTG/1owuMG1ejZR8hkSU5H/o3a1+H3Fv8OpuF/F3JKUfxoDl8LTM6n1eydza8IAI8A0/i+VY8ZskAfRhCeF9LJE17KBeTAHhx+aodx2atBLEVOhWy8OHUlbJ58C+2FoRhkQl4XSdPasZCd1lmRFp3Pz+pAEJTx4TDkScY3jvfEg0E66onJxXhbeNtn9iOEgUmdrxNZzKDgHbjajcMWZPg62Tyt0x/ILFg7K5UmKt71ENm+hMssFTOWvwS0B9TnPxKIA0NZ/GKTNVPoC0Uylh9GGEMY6m4Oth93eDN2IiJ0VxkdVC7Bi2ffWAd27gudzb8kO/5g0j/wYMt17KWQfvnOjOBDVP1efm6Sy1kdDHjavjc5o3Q/ouN/+rlc6o2d4IJddZ6vnT6zGwcbe+3lEWu282vrm22f5Bi4Nzd0ueJ2ja49lqIkRtMixwakm6RDPR+Swqlex7cD6UDYsBY1PMToB3r3rvYCYXNjeGikj1rt6X7+WSWtcbOEB14aPQD5l7tWhKnHpoZ9U2KYgJ31JMoCUBHS/3nm2m8ePxoGIp6Szr+Olorvdeq3pySy4RUiiReZ1ECAAvG2EM1kjqVC2jrJyaHson1a8/KQ4OjH59V3Ntu3dt5B9TvkqQOy1wCByWMC/x0=
