language: node_js

node_js:
  - '11'
  - node

branches:
  only:
    - master

script:
  - yarn
  - yarn build
  - yarn test
  - yarn test:coverage

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
